---

- name: Common Kubernetes components on control and worker nodes
  become: yes
  hosts: all

  roles: 
    - bootstrap_os
    - containerd
    - k8_components

- name: Initialize Kubernetes Control Plane
  hosts: control_plane
  become: yes

  roles:
    - control_plane
    - cni
 

- name: Join Worker Nodes
  hosts: worker_nodes
  become: yes

  roles:
    - worker_plane
