---

- name: Common Kubernetes components on control and worker nodes
  become: yes
  hosts: all

  roles: 
    - bootstrap_os
    - containerd
    - k8_components

- name: Initialize Kubernetes Control Plane
  hosts: ControlPlane
  become: yes

  roles:
    - control_plane
    - cni
 

- name: Join Worker Nodes
  hosts: WorkerNodes
  become: yes

  roles:
    - worker_nodes


- name: cluster status
  hosts: ControlPlane
  
  roles: 
    - podcheck